import org.jetbrains.kotlin.gradle.plugin.mpp.NativeOutputKind

plugins {
  alias(libs.plugins.publish)
  alias(libs.plugins.dokka)
  id("app.cash.sqldelight.multiplatform")
  id("app.cash.sqldelight.toolchain.runtime")
  //alias(libs.plugins.binaryCompatibilityValidator)
  id("kotlinx-atomicfu")
}

archivesBaseName = 'sqldelight-coroutines-extensions'

kotlin {
  applyDefaultHierarchyTemplate {
    it.common {
      // not using commonTest due https://github.com/touchlab/SQLiter/issues/117
      it.group("testable") {
        it.withJvm()
        it.withOhosArm64()
      }
    }
  }

  sourceSets {
    commonMain.dependencies {
      api projects.runtime
      api libs.kotlin.coroutines.core
      implementation project(":extensions:async-extensions")
    }
  }
}

apply from: "$rootDir/gradle/gradle-mvn-push.gradle"
